---
# Source: namespace-deploy/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: demo
type: Opaque
data:
  key1: dmFsdWUx

# kubectl get secret
# echo -n dmFsdWUx | base64 -d